let bankinh=parseFloat(prompt("Mời bạn nhập vào bán kính"))
let chieucao=parseFloat(prompt("Mời bạn nhập vào chiều cao"))
let sxq=(2*Math.PI*bankinh*chieucao)
document.write(`Diện tích xung quanh của hình trụ là ${sxq} <br>`)
let stp=(2*Math.PI * bankinh*(bankinh+chieucao))
document.write(`Diện tích toàn phần của hình trụ là:${stp} <br>`)
let thetich=(Math.PI * Math.pow(bankinh,2)*chieucao)
document.write(`Thể tích hình trụ là ${thetich} <br>`)
let chuviday=(Math.PI * bankinh * 2)
document.write(`Chu vi đấy của hình trụ là ${chuviday}`)